### ISSUE TITLE
Draw the transparent background

### ISSUE THREAD

**Issue by kevinnroan** [metal-by-example/metal-spatial-rendering#1]
Hi @warrenm ,

Thank you for sharing this demo.
Btw, I have a question.
How can draw the transparent background, instead of draw the envinroment?
If I comment out this [line](https://github.com/metal-by-example/metal-spatial-rendering/blob/fecc461d88652c55bf2f7ef81838a798c7d65581/FullyImmersiveMetal/FullyImmersiveMetal/SpatialRenderer.mm#L111C17-L111C17), then I see the black background. but I wanted to see the simultor built-in original room.
And also, could you let me let how can the viewport size? 
Please help me. I am very element entry coder, but my client want to see my demo :)

**Comment by warrenm** [comment]
It is not possible to composite custom Metal content atop a passthrough view, nor is it possible to render a passthrough view yourself in a fully immersive space. This limitation was covered exhaustively in the WWDC sessions pertaining to visionOS. If you need to render spatial content in a shared or partially immersive space, I recommend using higher-level APIs like RealityKit or Unity.
