### ISSUE TITLE
From Xcode 15 beta 8 use of "Pose" should be changed to "Device Anchor"

### ISSUE THREAD

**Issue by Verlet** [metal-by-example/metal-spatial-rendering#4]
Heads up! From Xcode 15 beta 8 "Pose" is renamed to "Device Anchor".
eg. use `ar_world_tracking_provider_query_device_anchor_at_timestamp(…)` instead of `ar_world_tracking_provider_query_pose_at_timestamp(…)`

Cheers!

**Comment by warrenm** [comment]
Sorry for the late reply. I think we're back up to date with [f650ffd](https://github.com/metal-by-example/metal-spatial-rendering/commit/f650ffd1e682d51a2b0e578cab6a0b58a5415177).

**Comment by warrenm** [comment]
Calling this done.
